name: 'Lighthouse User Flow CI Action'
description: "Audit URL's using Lighthouse user flow and test performance within PR's"
inputs:
  # GLOBAL ============================================
  rcPath:
    description: 'Path to a UFCI user-flowrc.json file'
    required: false
    default: '.user-flowrc.json'
  verbose:
    description: 'Verbose logging flag ("on" or "off")'
    required: false
    # has to be in line with @push-based/user-flow/packages/cli/src/lib/pre-set.ts#CI_PRESET
    default: 'off'
  dryRun:
    description: 'Faster runs due to dummy results for reports ("on" or "off")'
    required: false
    # has to be in line with @push-based/user-flow/packages/cli/src/lib/pre-set.ts#CI_PRESET
    default: 'off'
runs:
  using: "composite"
  steps:
    - name: run:user-flow
      id: ruf
      shell: bash
      run: node ${{ github.action_path }}/dist/packages/user-flow-gh-action/main.js
      env:
        INPUT_RCPATH: ${{ inputs.rcPath }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
        INPUT_DRYRUN: ${{ inputs.dryRun }}
    - name: Add reduced report as comment to the PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        hide_and_recreate: true # collapse old comment, mark it as outdated and append new
        header: user flow summary report
        message: ${{ steps.ruf.outputs.resultSummary }}
branding:
  icon: 'bar-chart-2' # un-sorted bar chart
  color: 'gray-dark'
